services:

  backend:
    build: ./stream-backend
    container_name: streaming-backend
    depends_on:
      - mysql
      - redis
      - elasticsearch
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: jdbc:mysql://mysql-db:3308/streaming_platform
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: test
      REDIS_HOST: redis-cache
      REDIS_PORT: 6379
      ELASTICSEARCH_URL: search-searvice:9200
      ELASTICSEARCH_USERNAME: root
      ELASTICSEARCH_PASSWORD: test
      FFMPEG_URL: http://stream-converter:5000
      JWT_SECRET_KEY: 5c990cfd4f3c3b57b61107ebc5e1d44367586d2d2b170e4bf5bfbb1c613b3470
      MAIL_LOST: smtp.gmail.com
      MAIL_USERNAME: misfit.dev.13@gmail.com
      MAIL_PASSWORD: hgjwouvpepzfyeff
    volumes:
      - E:/FullStack-Learning/StreamingPlatform/Videos:/videos
      - E:/FullStack-Learning/StreamingPlatform/profile-pic:/profile-pics

  frontend:
    build: ./stream-frontend
    container_name: streaming-frontend
    ports:
      - "5173:3000"

  nginx-rtmp:
    build: ./nginx-rtmp
    container_name: rtmp-server
    ports:
      - "1935:1935"
      - "8000:8080"
    volumes:
      - E:/FullStack-Learning/StreamingPlatform/recordings:/tmp/recordings
      - E:/FullStack-Learning/StreamingPlatform/nginx-live-videos:/mnt/hls/
    extra_hosts:
    - "host.docker.internal:host-gateway"

  ffmpeg-worker:
    build: ./ffmpeg-worker
    container_name: stream-converter
    ports:
      - "5000:5000"
    volumes:
      - E:/FullStack-Learning/StreamingPlatform/Videos:/worker/output
      - E:/FullStack-Learning/StreamingPlatform/recordings:/worker/input
    environment:
      REDIS_HOST: redis

  redis:
    image: redis:alpine
    container_name: redis-cache
    ports:
      - "6379:6379"

  mysql:
    image: mysql:8
    container_name: mysql-db
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: streaming_platform
    volumes:
      - mysql-data:/var/lib/mysql

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    container_name: search-searvice
    environment:
      discovery.type: single-node
      xpack.security.enabled: false
    ports:
      - "9200:9200"
    volumes:
      - es-data:/usr/share/elasticsearch/data

volumes:
  mysql-data:
  es-data:
