spring.application.name=StreamingPlatform

#For Port number
server.port=8080
server.address=0.0.0.0


#For database
spring.datasource.url=${DATABASE_URL:jdbc:mysql://localhost:3308/streaming_platform}
spring.datasource.username=${DATABASE_USERNAME:root}
spring.datasource.password=${DATABASE_PASSWORD:test}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#For hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Redis configuration
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

# Elasticsearch Configuration
elasticsearch.url=${ELASTICSEARCH_URL:localhost:9200}
#elasticsearch.username=${ELASTICSEARCH_USERNAME:root}
#elasticsearch.password=${ELASTICSEARCH_PASSWORD:test}
logging.console.enabled=false
logging.level.org.elasticsearch=OFF
logging.level.org.springframework.data.elasticsearch=OFF
logging.level.org.apache.http=ERROR


# FFMpeg converter
ffmpeg.url=${FFMPEG_URL:http://localhost:5000}

#For Windows file paths
videos.path=${VIDEO_PATH:E:/FullStack-Learning/StreamingPlatform/Videos}
profile-picture.path=${PROFILE_PICTURE_PATH:E:/FullStack-Learning/StreamingPlatform/profile-pic}
live.videos.path=${LIVE_PATH:E:/FullStack-Learning/StreamingPlatform/nginx-live-videos}

#videos.path=/videos
#profile-picture.path=/profile-pics
#live.videos.path=/nginx-live-path


#JWT security key
jwt.secret.key=${JWT_SECRET_KEY:5c990cfd4f3c3b57b61107ebc5e1d44367586d2d2b170e4bf5bfbb1c613b3470}

#Upload file size
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

#For Gmail services
spring.mail.host=${MAIL_LOST:smtp.gmail.com}
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:misfit.dev.13@gmail.com}
spring.mail.password=${MAIL_PASSWORD:hgjwouvpepzfyeff}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true